# This is a base image created out of ubuntu:latest
FROM ubuntu:xenial

MAINTAINER alihhussain <alihhussain@live.com>

ADD ./ /root/
 
RUN echo "Live Demo 2" > /tmp/livedemo2.txt
ENTRYPOINT ["/bin/bash"]
