FROM ubuntu:latest
MAINTAINER Ali Hussain "alhussai@microsoft.com"
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY . /app
RUN pip install -r requirements.txt
ENTRYPOINT ["/usr/bin/python", "/root/app/app.py"]