apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: info-app-enhanced
    image: 10thmag.azurecr.io/azurepublic:info-app-enhanced
  imagePullSecrets:
  - name: regcred

